# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  rootpath: '$(Pipeline.Workspace)'

stages:
- stage: Build
  displayName: Build
  jobs:  
  - job: Build_activityapi
    displayName: Build activityapi
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push activityapi image
      inputs:
        containerRegistry: 'docker hub'
        repository: 'togetherhub/activityapi'
        command: 'buildAndPush'
        buildContext: .
        Dockerfile: 'src/microservices/Activity/Activity.API/Dockerfile'
        tags: 
          $(tag)
  - job: Build_messagingapi
    displayName: Build messagingapi
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push messagingapi image
      inputs:
        containerRegistry: 'docker hub'
        repository: 'togetherhub/messaginghost'
        command: 'buildAndPush'
        buildContext: .
        Dockerfile: 'src/microservices/Messaging/Messaging.API/Dockerfile'
        tags: 
          $(tag)

- stage: Deploy
  displayName: Deploy
  jobs:  
  - job: Deploy_activityapi
    displayName: Deploy activityapi
    pool:
      vmImage: 'ubuntu-latest'
    steps:  
    - task: HelmDeploy@0
      displayName: Deploy activityapi
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: 'Azure 订阅 (03289134-4bce-463d-82e1-5147f05443b3)'
        azureResourceGroup: 'together-group'
        kubernetesCluster: 'together-aks'
        namespace: 'together'
        command: 'upgrade'
        chartType: 'FilePath'
        chartPath: 'k8s/helm/activityapi'
        releaseName: 'activityapi'
        arguments: '-f $(rootpath)/s/k8s/helm/inf.yaml'
        overrideValues: 'image.tag=$(tag)'
  - job: Deploy_messagingapi
    displayName: Deploy messagingapi
    pool:
      vmImage: 'ubuntu-latest'
    steps:  
    - task: HelmDeploy@0
      displayName: Deploy messagingapi
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: 'Azure 订阅 (03289134-4bce-463d-82e1-5147f05443b3)'
        azureResourceGroup: 'together-group'
        kubernetesCluster: 'together-aks'
        namespace: 'together'
        command: 'upgrade'
        chartType: 'FilePath'
        chartPath: 'k8s/helm/messagingapi'
        releaseName: 'messagingapi'
        overrideValues: 'image.tag=$(tag)'