# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  rootpath: '$(Pipeline.Workspace)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push activityapi image
      inputs:
        containerRegistry: 'docker hub'
        repository: 'zengande/activityapi'
        command: 'buildAndPush'
        buildContext: .
        Dockerfile: 'src/microservices/Activity/Activity.API/Dockerfile'
        tags: 
          $(tag)
- stage: Deploy
  displayName: Deploy services
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:  
    - task: HelmDeploy@0
      displayName: Deploy activityapi
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: 'Azure 订阅 (03289134-4bce-463d-82e1-5147f05443b3)'
        azureResourceGroup: 'together-group'
        kubernetesCluster: 'together-aks'
        namespace: 'together'
        command: 'upgrade'
        chartType: 'FilePath'
        chartPath: 'deploy/k8s/helm/activityapi'
        releaseName: 'activityapi'
        arguments: '-f $(rootpath)/s/deploy/k8s/helm/inf.yaml'
        overrideValues: 'image.tag=$(tag)'
        