{{- $fullName := include "activityapi.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: cfg-{{ $fullName }}
  labels:
    app: {{ template "activityapi.name" . }}
    chart: {{ template "activityapi.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  activity__DefaultConnection: server=mysql.together;user id=root;password={{ .Values.inf.mysql.password }};database={{ .Values.inf.activity.db }};charset=utf8;sslMode=None;
  rabbitmq__HostName: rabbitmq-rabbitmq-ha-discovery.together.svc.cluster.local
  rabbitmq__UserName: {{ .Values.inf.rabbitmq.username }}
  rabbitmq__Password: {{ .Values.inf.rabbitmq.password }}
  activity__SwaggerUIClientId: {{ .Values.inf.activity.swaggerUIClientId }}
  activity__clientId: {{ .Values.inf.activity.clientId }}
  aad__Tenant: {{ .Values.inf.aad.tenant }}
  aad__SiginSignupPolicy: {{ .Values.inf.aad.siginSignupPolicy }}