FROM mcr.microsoft.com/dotnet/core/sdk:3.1
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://+:80
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src
COPY ["src/buildingblocks/BuildingBlocks.Domain/BuildingBlocks.Domain.csproj", "src/buildingblocks/BuildingBlocks.Domain/"]
COPY ["src/buildingblocks/BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure.csproj", "src/buildingblocks/BuildingBlocks.Infrastructure/"]
COPY ["src/microservices/Activity/Activity.API/Activity.API.csproj", "src/microservices/Activity/Activity.API/"]
COPY ["src/microservices/Activity/Activity.Application/Activity.Application.csproj", "src/microservices/Activity/Activity.Application/"]
COPY ["src/microservices/Activity/Activity.Domain/Activity.Domain.csproj", "src/microservices/Activity/Activity.Domain/"]
COPY ["src/microservices/Activity/Activity.Infrastructure/Activity.Infrastructure.csproj", "src/microservices/Activity/Activity.Infrastructure/"]

RUN dotnet restore "src/microservices/Activity/Activity.API/Activity.API.csproj"
COPY . .
WORKDIR "/src/src/microservices/Activity/Activity.API"
RUN dotnet build --no-restore "Activity.API.csproj" -c $BUILD_CONFIGURATION

RUN echo "exec dotnet run --no-build --no-launch-profile -c $BUILD_CONFIGURATION --" > /entrypoint.sh

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]