FROM mcr.microsoft.com/dotnet/core/sdk:3.1
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://+:80
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src
COPY ["src/buildingblocks/BuildingBlocks.Domain/BuildingBlocks.Domain.csproj", "src/buildingblocks/BuildingBlocks.Domain/"]
COPY ["src/buildingblocks/BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure.csproj", "src/buildingblocks/BuildingBlocks.Infrastructure/"]
COPY ["src/microservices/Messaging/Messaging.API/Messaging.API.csproj", "src/microservices/Messaging/Messaging.API/"]
COPY ["src/microservices/Messaging/Messaging.Application/Messaging.Application.csproj", "src/microservices/Messaging/Messaging.Application/"]
COPY ["src/microservices/Messaging/Messaging.Domain/Messaging.Domain.csproj", "src/microservices/Messaging/Messaging.Domain/"]
COPY ["src/microservices/Messaging/Messaging.Infrastructure/Messaging.Infrastructure.csproj", "src/microservices/Messaging/Messaging.Infrastructure/"]

RUN dotnet restore "src/microservices/Messaging/Messaging.API/Messaging.API.csproj"
COPY . .
WORKDIR "/src/src/microservices/Messaging/Messaging.API"
RUN dotnet build --no-restore "Messaging.API.csproj" -c $BUILD_CONFIGURATION

RUN echo "exec dotnet run --no-build --no-launch-profile -c $BUILD_CONFIGURATION --" > /entrypoint.sh

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]