// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;
using Together.UserGroup.API.Infrastructure.Data;

namespace Together.UserGroup.API.Migrations
{
    [DbContext(typeof(UserGroupDbContext))]
    [Migration("20180430044426_InitDatabase")]
    partial class InitDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Together.UserGroup.API.Infrastructure.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Founder")
                        .HasMaxLength(50);

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Introduction")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("groups");
                });

            modelBuilder.Entity("Together.UserGroup.API.Infrastructure.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar")
                        .HasMaxLength(200);

                    b.Property<DateTime?>("Birthday");

                    b.Property<int?>("GroupId");

                    b.Property<string>("Nickname")
                        .HasMaxLength(50);

                    b.Property<int?>("Sex");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Together.UserGroup.API.Infrastructure.Models.User", b =>
                {
                    b.HasOne("Together.UserGroup.API.Infrastructure.Models.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId");
                });
#pragma warning restore 612, 618
        }
    }
}
